version: '3.8'
services:
   web:
       build: .
       env_file:
           - .env
       command: python manage.py runserver 0.0.0.0:8000
       ports:
           - 8000:8000
       depends_on:
           - "postgres"
   postgres:
       image: postgres:latest
       env_file:
           - .env
       ports:
           - 5432:5432